# 4.1 특성 스케일 바꾸기

In [1]:
# MinMaxScaler 사용

In [2]:
import numpy as np
from sklearn import preprocessing

In [5]:
feature = np.array([[-500.5],
                   [-100.1],
                   [0],
                   [100.1],
                   [900.9]])

In [6]:
# 스케일러 객체 만들기
minmax_scale = preprocessing.MinMaxScaler(feature_range = (0, 1))

In [7]:
# 특성의 스케일을 변환하기
scaled_feature = minmax_scale.fit_transform(feature)

In [8]:
# 특성을 출력하기
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

스케일 조정은 머신러닝에서 흔한 전처리 작업이다.\
최솟값과 최댓값을 사용하여 일정 범위 안으로 값을 조정한다.\
xi' = xi-min(x) / max(x)-min(x)\
\
xi는 특성 x의 개별 원소이고, xi는 특성 백터이다.

######
훈련 세트와 테스트 세트의 스케일을 따로 조정하면 안된다. 예를 들면 훈련 세트의 스케일을 조정하고자 구한 최솟값과 최댓값을 사용하여 테스트 세트를 반환해야 한다. 아래는 간단한 예 이다.\\

\
다음 샘플 중 처음 세개를 훈련 세트, 나머지 두 개를 테스트 세트라고 가정해본다.\
먼저 두 세트를 독립적으로 각각 변환한다.

In [9]:
# 훈련 세트를 변환한다.
preprocessing.MinMaxScaler().fit_transform(feature[:3])

array([[0. ],
       [0.8],
       [1. ]])

In [10]:
# 테스트 세트를 변환한다.
preprocessing.MinMaxScaler().fit_transform(feature[3:])

array([[0.],
       [1.]])

훈련 세트와 테스트 세트를 각각 변환하면 서로 다른 비율로 데이터를 변환한다. 이러면 안됨.

In [14]:
# 훈련 세트로 변환기를 학습한다.
scaler = preprocessing.MinMaxScaler().fit(feature[:3])
scaler.transform(feature[:3])

array([[0. ],
       [0.8],
       [1. ]])

In [15]:
# 훈련 세트에서 학습한 변환기로 테스트 세트를 변환한다.
scaler.transform(feature[3:])

array([[1.2],
       [2.8]])

훈련 세트를 학습한 변환기 객체를 사용하여 원본 데이터셋과 동일한 비률로 테스트를 변환했다.

# 4.2 특성을 표준화하기

In [16]:
x = np.array([[-1000.1],
             [-200.2],
             [500.5],
             [600.6],
             [9000.9]])

In [17]:
# 변환기 객체 만들기.
scaler = preprocessing.StandardScaler()

In [18]:
# 특성을 변환한다.
standardized = scaler.fit_transform(x)

In [19]:
# 특성을 출력한다.
standardized

array([[-0.76058269],
       [-0.54177196],
       [-0.35009716],
       [-0.32271504],
       [ 1.97516685]])

4.1에서 설명한 최소-최대 스케일링과 함께 특성을 표준 정규분포로 근사하는 스케일링 방식이 자주 쓰인다.\
이 방식은 표준화를 사용하여 데이터의 평균이 0이고 표준편차가 1이 되도록 변환한다.

이 방식은 머신러닝에서 상당히 많이 쓰인다. 하지만 학습 알고리즘에 의존적이다.\
예를 들어 주성분 분석은 표준화가 잘 맞지만 신경망에는 최소-최대 스케일링을 종종 권장한다.

In [23]:
# 평균과 표준편차를 출력한다,
print('평균:', round(standardized.mean()))
print('표준편차:', standardized.std())

평균: 0
표준편차: 1.0


이상치가 많을 경우엔 중간값과 사분위 범위를 사용하여 특성의 스케일을 조정하는 것이 좋다. RobusScaler

In [24]:
# 변환기 객체를 만든다.
robust_scaler = preprocessing.RobustScaler()

In [25]:
# 특성을 변환한다.
robust_scaler.fit_transform(x)

array([[-1.87387612],
       [-0.875     ],
       [ 0.        ],
       [ 0.125     ],
       [10.61488511]])

RobusScaler는 데이터에서 중간값을 빼고 IQR로 나눈다.

In [26]:
interquatile_range = x[3] - x[1]

(x - np.median(x)) / interquatile_range

array([[-1.87387612],
       [-0.875     ],
       [ 0.        ],
       [ 0.125     ],
       [10.61488511]])

QuantileTransformer는 훈련 데이터를 1,000개의 분위로 나누어 0~1 사이에 고르게 분포시킴으로써 이상치로 인한 영향을 줄인다.\
예를 들어 해결에 나온 특성 x는 다섯 개의 샘플을 가지고 있으므로 0%, 25%, 50%, 75%, 100%의 위치에 할당한다.

In [27]:
preprocessing.QuantileTransformer().fit_transform(x)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_data.py:2367: UserWarning: n_quantiles (1000) is greater than the total number of samples (5). n_quantiles is set to n_samples.
  warnings.warn("n_quantiles (%s) is greater than the total number "


array([[0.  ],
       [0.25],
       [0.5 ],
       [0.75],
       [1.  ]])

# 4.3 정규화하기

In [3]:
import numpy as np
from sklearn.preprocessing import Normalizer

In [4]:
# 특성 행렬 만들기
features = np.array([[0.5, 0.5],
                    [1.1, 3.4],
                    [1.5, 20.2],
                    [1.63, 34.3],
                    [10.9, 3.3]])

In [5]:
# 변환기 객체 만들기
normalizer = Normalizer(norm = 'l2')

In [6]:
# 특성 행렬을 변환한다.
normalizer.transform(features)

array([[0.70710678, 0.70710678],
       [0.30782029, 0.95144452],
       [0.07405353, 0.99725427],
       [0.0474683 , 0.99887275],
       [0.95709822, 0.28976368]])

Normalizer는 단위 노름(길이의 합이 1이다)이 되도록 개별 샘플의 값을 변환한다.\
이런 종류의 스케일링은 (예를 들어 각 단어나 n개의 단어 그룹이 특성인 텍스트 분류와 같이) 유사한 특성이 많을 때 종종 사용한다.

In [7]:
# 특성 행렬을 변환한다.
features_l2_norm = Normalizer(norm = 'l2').transform(features)

In [9]:
# 특성 행렬을 출력한다.
features_l2_norm

array([[0.70710678, 0.70710678],
       [0.30782029, 0.95144452],
       [0.07405353, 0.99725427],
       [0.0474683 , 0.99887275],
       [0.95709822, 0.28976368]])

In [10]:
# 맨해튼 노름(l1)을 지정할 수도 있다.
# 특성 행렬을 변환한다.
features_l1_norm = Normalizer(norm = 'l1').transform(features)

In [11]:
# 특성 행렬을 출력한다.
features_l1_norm

array([[0.5       , 0.5       ],
       [0.24444444, 0.75555556],
       [0.06912442, 0.93087558],
       [0.04536599, 0.95463401],
       [0.76760563, 0.23239437]])

l2 노름은 뉴욕의 두 지점 사이를 잇는 직선 거리로 볼 수 있다.\
l1 노름은 사람이 도로를 따라 걷는 것과 같다.\
이를 '맨해튼 노름', '택시 노름'으로 부른다.

In [12]:
# norm = 'l1'은 각 샘플 특성값의 합을 1로 만든다.
# 합을 출력한다.

print('첫 번째 샘플값의 합: ',
     features_l1_norm[0, 1] + features_l1_norm[0, 1])

첫 번째 샘플값의 합:  1.0


Normalizer는 행 단위로 변환되므로 fit 메서드는 아무런 작업을 수행하지 않는다.\
이런 이유로 해결의 코드처럼 바로 transform 메서드를 사용할 수 있다.

In [13]:
# L1 노름을 사용한 변환.
# 각 행(axis = 1)을 합한 결과가 2차원 배열로 유지되도록
# keepdims를 True로 설정한다.

features / np.sum(np.abs(features), axis = 1, keepdims = True)


array([[0.5       , 0.5       ],
       [0.24444444, 0.75555556],
       [0.06912442, 0.93087558],
       [0.04536599, 0.95463401],
       [0.76760563, 0.23239437]])

In [15]:
# L2 노름을 사용한 변환
features / np.sqrt(np.sum(np.square(features), axis = 1, keepdims = True))

array([[0.70710678, 0.70710678],
       [0.30782029, 0.95144452],
       [0.07405353, 0.99725427],
       [0.0474683 , 0.99887275],
       [0.95709822, 0.28976368]])

Normalizer의 norm 매개변수에 지정할 수 있는 다른 한 가지 옵션은 'max'이다. 이 옵션은 단순히 각 행의 최댓값으로 행의 값을 나눈다.

In [16]:
# 각 행에서 최댓값으로 나눈다.
Normalizer(norm = 'max').transform(features)

array([[1.        , 1.        ],
       [0.32352941, 1.        ],
       [0.07425743, 1.        ],
       [0.04752187, 1.        ],
       [1.        , 0.30275229]])

# 4.4 다항 특성과 교차항 특성 생성하기

In [18]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures

In [19]:
features = np.array([[2, 3],
                    [2, 3],
                    [2, 3]])

In [20]:
Polynomial_interaction = PolynomialFeatures(degree = 2, include_bias = False)

In [22]:
# 다항 특성 만들기.
Polynomial_interaction.fit_transform(features)

array([[2., 3., 4., 6., 9.],
       [2., 3., 4., 6., 9.],
       [2., 3., 4., 6., 9.]])

degree 매개변수가 다항식의 최대 차수를 결정한다.\
예를 들어 degree = 2는 2제곱까지 새로운 특성을 만든다.\
x1,x2,x1(2),x2(2)\
\
degree=3은 3제곱까지 새로운 특성을 만든다.\
x1,x2,x1(2),x2(2),x1(3),x2(3)

기본적으로 PolynomialFeatrues는 교차항을 포함한다.\
interaction_only를 True로 지정하면 교차항 특성만 만들 수 있다.

In [23]:
interaction = PolynomialFeatures(degree = 2,
                                interaction_only = True, include_bias = False)
interaction.fit_transform(features)

array([[2., 3., 6.],
       [2., 3., 6.],
       [2., 3., 6.]])

특성과 타깃 사이에 비선형 관계가 있다는 가정을 추가할 때 다항 특성을 종종 만든다.\
개별 특성을 곱한 교차항을 특성에 추가하여 이런 관계를 인코딩할 수 있다.(예시: 커피당도)

In [24]:
# 상수항 1을 추가한다.
polynomial_bias = PolynomialFeatures(degree = 2,
                                    include_bias = True).fit(features)
polynomial_bias.transform(features)

array([[1., 2., 3., 4., 6., 9.],
       [1., 2., 3., 4., 6., 9.],
       [1., 2., 3., 4., 6., 9.]])

In [25]:
# get_feature_names 메서드는 특성 변환 식을 이름으로 반환한다.
polynomial_bias.get_feature_names()

['1', 'x0', 'x1', 'x0^2', 'x0 x1', 'x1^2']

# 4.5 특성 변환하기

In [26]:
import numpy as np
from sklearn.preprocessing import FunctionTransformer

In [27]:
features = np.array([[2, 3],
                    [2, 3],
                    [2, 3]])

In [28]:
def add_ten(x):
    return x + 10

In [29]:
ten_transformer = FunctionTransformer(add_ten)

In [30]:
ten_transformer.transform(features)

array([[12, 13],
       [12, 13],
       [12, 13]])

판다스의 apply 메서드를 사용하여 동일한 변환을 수행할 수 있다.

In [31]:
import pandas as pd

In [32]:
df = pd.DataFrame(features, columns = ['feature_1', 'featrue_2'])

In [33]:
df.apply(add_ten)

feature_1  featrue_2
0         12         13
1         12         13
2         12         13

In [35]:
# validate가 False이면 일차원 배열에도 적용할 수 있다.
FunctionTransformer(add_ten, validate = False).transform(np.array([1, 2, 3]))

array([11, 12, 13])

In [36]:
# ColumnTransformer를 사용하면 특성 배열이나 데이터프레임의 열마다 다른 변환을 적용할 수 있다.
from sklearn.compose import ColumnTransformer

In [37]:
def add_hundred(x):
    return 100 + x

In [43]:
# 이름, 변환기, 열 리스트 로 구성된 튜플의 리스트를
# ColumnTransformer에 전달한다.

ct = ColumnTransformer([('add_ten', FunctionTransformer(add_ten, validate = True), ['feature_1']),
 ('add_hundred', FunctionTransformer(add_hundred, validate = True),['feature_2'])])

ct.fit_transform(df)

ValueError: A given column is not a column of the dataframe

# 4.6 이상치 감지하기

일반적인 방법으로 데이터가 정규분포를 따른다고 가정하고 이런 가정을 기반으로 데이터를 둘러싼 타원을 그린다.\
이 타원 안의 샘플을 정상치(레이블 1)로 분류하고,  타원 밖의 샘플은 이상치(레이블 - 1)로 분류한다.

In [44]:
import numpy as np
from sklearn.covariance import EllipticEnvelope
from sklearn.datasets import make_blobs

In [45]:
# 모의 데이터
features, _ = make_blobs(n_samples = 10,
                        n_features = 2,
                        centers =1,
                        random_state = 1)

In [48]:
features, _

(array([[-1.83198811,  3.52863145],
        [-2.76017908,  5.55121358],
        [-1.61734616,  4.98930508],
        [-0.52579046,  3.3065986 ],
        [ 0.08525186,  3.64528297],
        [-0.79415228,  2.10495117],
        [-1.34052081,  4.15711949],
        [-1.98197711,  4.02243551],
        [-2.18773166,  3.33352125],
        [-0.19745197,  2.34634916]]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))

In [49]:
# 첫 번째 샘플을 극단적인 값으로 바꾼다.
features[0, 0] = 10000
features[0, 1] = 10000

In [50]:
# 이상치 감지 객체를 만든다.
outlier_detector = EllipticEnvelope(contamination = .1)

In [51]:
# 감지 객체를 훈련한다.
outlier_detector.fit(features)

EllipticEnvelope()

In [52]:
# 이상치를 예측한다.
outlier_detector.predict(features)

array([-1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

# 4.7 이상치 다루기

In [1]:
import pandas as pd

In [2]:
houses = pd.DataFrame()
houses['Price'] = [534433, 392333, 293222, 4322032]
houses['Bathrooms'] = [2, 3.5, 2, 116]
houses['Square_Feet'] = [1500, 2500, 1500, 48000]

In [3]:
# 샘플 필터링
houses[houses['Bathrooms'] < 20]

Price  Bathrooms  Square_Feet
0  534433        2.0         1500
1  392333        3.5         2500
2  293222        2.0         1500

In [4]:
# 두 번째는 이상치로 표시하고 이를 특성의 하나로 표함시킨다.
import numpy as np

In [5]:
# 불리언 조건을 기반으로 특성을 만든다.
houses['Outlier'] = np.where(houses['Bathrooms'] < 20, 0, 1)

In [6]:
houses

Price  Bathrooms  Square_Feet  Outlier
0   534433        2.0         1500        0
1   392333        3.5         2500        0
2   293222        2.0         1500        0
3  4322032      116.0        48000        1

In [9]:
# 마지막으로 이상치의 영향이 줄어들도록 특성을 변환한다.
# 로그 특성
houses['Log_Of_Square_Feet'] = [np.log(x) for x in houses['Square_Feet']]
houses

Price  Bathrooms  Square_Feet  Outlier  Log_Of_Square_Feet
0   534433        2.0         1500        0            7.313220
1   392333        3.5         2500        0            7.824046
2   293222        2.0         1500        0            7.313220
3  4322032      116.0        48000        1           10.778956

이상치는 분석 목적에 맞게 잘 선택하여 처리한다.\
RobustSclaer 와 같이 이상치에 민감하지 않은 스케일링 방법을 사용하라.

# 4.8 특성 이산화하기

In [10]:
import numpy as np
from sklearn.preprocessing import Binarizer

In [11]:
age = np.array([[6],
               [12],
               [20],
               [36],
               [65]])

In [12]:
binarizer = Binarizer(18)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:67: FutureWarning: Pass threshold=18 as keyword args. From version 0.25 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.25 "


In [13]:
# 특성을 변환한다.
binarizer.fit_transform(age)

array([[0],
       [0],
       [1],
       [1],
       [1]])

In [14]:
# 여러 임계값에 따라 나누기
np.digitize(age, bins = [20, 30, 64])

array([[0],
       [0],
       [1],
       [2],
       [3]], dtype=int64)

bins 매개변수의 입력값은 각 구간의 왼쪽 경곗값이다.\
예를 들어 20까지 구간에는 값이 20인 원소가 포함되지 않고, 20보다 작은 두 개만 포함된다\
right 매개변수를 True로 설정하면 이 동작을 바꿀 수 있다.

In [16]:
np.digitize(age, bins = [20, 30, 64], right = True)

array([[0],
       [0],
       [0],
       [2],
       [3]], dtype=int64)

In [19]:
np.digitize(age, bins = [20, 30, 64], right = False)

array([[0],
       [0],
       [1],
       [2],
       [3]], dtype=int64)

이산화는 수치 특성을 범주형처럼 다루어야 할 때 유용한 전력이다.

In [21]:
# 두 개의 구간으로 나누기.
np.digitize(age, bins = [18])

array([[0],
       [0],
       [1],
       [1],
       [1]], dtype=int64)